# the file contains several test profiles for running either separate frontend, backend or combination
# profiles (scenarios):
#
# - api-only: backend only (hot reload, dev run), no frontend
# - mock-only: frontend only (hot reload, dev run), no backend
# - mock-dev: backend (hot reload, dev run) and frontend (hot reload, dev run)
# - mock-prod: backend (hot reload, dev run) and frontend (build, prod run)
#
# run with: docker compose -f compose.base.yaml -f compose.dev.yaml --profile [[profile]] up


x-extend-frontend: &extend-frontend
  extends:
    file: compose.base.yaml
    service: frontend
    volumes:
      - /app/node_modules               # anonymous volume to avoid overrides in host
      - /app/.next                      # anonymous volume to avoid overrides in host
  ports:
    - "3000:3000"


x-frontend-build-context: &frontend-build-context
  context: ./mock_frontend/shallwe
  args:
    NEXT_PUBLIC_SHALLWE_ENV_MODE: ${NEXT_PUBLIC_SHALLWE_ENV_MODE:?}
    NEXT_PUBLIC_SHALLWE_OAUTH_CLIENT_ID: ${NEXT_PUBLIC_SHALLWE_OAUTH_CLIENT_ID:?}
    NEXT_PUBLIC_SHALLWE_OAUTH_REDIRECT_URI: ${NEXT_PUBLIC_SHALLWE_OAUTH_REDIRECT_URI:?}
    NEXT_PUBLIC_SHALLWE_API_BASE_URL_EXTERNAL: ${NEXT_PUBLIC_SHALLWE_API_BASE_URL_EXTERNAL:?}
    NEXT_PUBLIC_SHALLWE_API_BASE_URL_INTERNAL: http://backend:8000
    NEXT_PUBLIC_SHALLWE_SKIP_MIDDLEWARE: ${NEXT_PUBLIC_SHALLWE_SKIP_MIDDLEWARE:?}


services:

  # include db (except mock-only)
  db:
    profiles:
      - mock-dev
      - mock-prod
      - api-only


  # backend overrides for local build and db (except mock-only)
  backend:
    build:
      context: ./shallwe_core
      args:
        SHALLWE_BACKEND_DEEPFACE_MODELS: ${SHALLWE_BACKEND_DEEPFACE_MODELS:?}
    volumes:
      - ./shallwe_core:/app             # mount code for hot reload
    ports:
      - "8000:8000"
    profiles:
      - mock-dev
      - mock-prod
      - api-only


  # mock frontend scenarios:
  # 1) use mock only (no backend)
  frontend-noapi:
    <<: *extend-frontend
    build:
      <<: *frontend-build-context
      target: dev
    volumes:
      - ./mock_frontend/shallwe:/app     # mount code for hot reload
    command: npm run dev:mock
    profiles:
      - mock-only

  # 2) use mock in dev mode with backend
  frontend-dev:
    <<: *extend-frontend
    build:
      <<: *frontend-build-context
      target: dev
    volumes:
      - ./mock_frontend/shallwe:/app     # mount code for hot reload
    command: npm run dev
    depends_on:
      - backend
    profiles:
      - mock-dev

  # 3) run the prod build with backend
  frontend-prod:
    <<: *extend-frontend
    build:
      <<: *frontend-build-context
      target: prod
    command: node server.js
    depends_on:
      - backend
    profiles:
      - mock-prod
