# the file contains a full setup for local QA run with NGINX
# profiles (scenarios):
#
# - qa: full run imitating prod setup (pulled prod images, no hot reload, nginx)
#
# run with: docker compose -f compose.base.yaml -f compose.qa.yaml --profile [[profile]] up


services:

  # include nginx
  nginx:
    profiles:
      - qa

  # include db
  db:
    profiles:
      - qa


  # backend overrides for qa
  backend:
    image: ${SHALLWE_GLOBAL_DOCKER_REGISTRY_URL}backend:${SHALLWE_GLOBAL_DOCKER_BACKEND_IMAGE_TAG:?}
    environment:
      SHALLWE_BACKEND_ENTRYPOINT_WORKERS_MULT: ${SHALLWE_BACKEND_ENTRYPOINT_WORKERS_MULT:?}
      SHALLWE_BACKEND_ENTRYPOINT_WORKERS_PRELOAD: ${SHALLWE_BACKEND_ENTRYPOINT_WORKERS_PRELOAD:?}
      SHALLWE_BACKEND_ENTRYPOINT_WORKERS_TIMEOUT: ${SHALLWE_BACKEND_ENTRYPOINT_WORKERS_TIMEOUT:?}
    profiles:
      - qa


  # run a preserved frontend build
  frontend:
    image: ${SHALLWE_GLOBAL_DOCKER_REGISTRY_URL}mock-frontend:${SHALLWE_GLOBAL_DOCKER_FRONTEND_IMAGE_TAG:?}
    command: node server.js
    depends_on:
      - backend
    profiles:
      - qa
