x-global-env: &global-env
  SHALLWE_GLOBAL_SITE_URL_EXTERNAL: ${SHALLWE_GLOBAL_SITE_URL_EXTERNAL:?}
  SHALLWE_GLOBAL_SITE_URL_INTERNAL: ${SHALLWE_GLOBAL_SITE_URL_INTERNAL:?}
  SHALLWE_GLOBAL_OAUTH_CLIENT_ID: ${SHALLWE_GLOBAL_OAUTH_CLIENT_ID:?}
  SHALLWE_GLOBAL_OAUTH_CLIENT_SECRET: ${SHALLWE_GLOBAL_OAUTH_CLIENT_SECRET:?}
  SHALLWE_GLOBAL_OAUTH_REDIRECT_URI: ${SHALLWE_GLOBAL_OAUTH_REDIRECT_URI:?}
  SHALLWE_GLOBAL_ENV_MODE: ${SHALLWE_GLOBAL_ENV_MODE:?}


services:

  backend:
    image: shallwe-backend:latest
    env_file:
      - path: .env
        required: false
      - path: .env.local
        required: false
    environment:
      # ---- globals ----
      <<: *global-env
      # ---- django core ----
      SHALLWE_BACKEND_SECRET_KEY: ${SHALLWE_BACKEND_SECRET_KEY:?}
      SHALLWE_BACKEND_DEBUG_ON: ${SHALLWE_BACKEND_DEBUG_ON:?}
      # ---- entrypoint ----
      SHALLWE_BACKEND_ENTRYPOINT_AUTORUN: ${SHALLWE_BACKEND_ENTRYPOINT_AUTORUN:?}
      SHALLWE_BACKEND_ENTRYPOINT_AUTOTEST: ${SHALLWE_BACKEND_ENTRYPOINT_AUTOTEST:?}
      # ---- admin ----
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME:?}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL:?}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD:?}
      # ---- database ----
      SHALLWE_BACKEND_DB_HOST: ${SHALLWE_BACKEND_DB_HOST:?}
      SHALLWE_BACKEND_DB_PORT: ${SHALLWE_BACKEND_DB_PORT:?}
      SHALLWE_BACKEND_DB_NAME: ${SHALLWE_BACKEND_DB_NAME:?}
      SHALLWE_BACKEND_DB_USER: ${SHALLWE_BACKEND_DB_USER:?}
      SHALLWE_BACKEND_DB_PASS: ${SHALLWE_BACKEND_DB_PASS:?}
      # ---- network ----
      SHALLWE_BACKEND_ALLOWED_HOSTS: ${SHALLWE_BACKEND_ALLOWED_HOSTS:?},backend
      SHALLWE_BACKEND_CSRF_TRUSTED_ORIGINS: ${SHALLWE_BACKEND_CSRF_TRUSTED_ORIGINS:?}
      SHALLWE_BACKEND_CORS_ALLOWED_ORIGINS: ${SHALLWE_BACKEND_CORS_ALLOWED_ORIGINS:?}
      SHALLWE_BACKEND_CREDENTIALS_COOKIE_DOMAIN: ${SHALLWE_BACKEND_CREDENTIALS_COOKIE_DOMAIN}
      # ---- logs ----
      TF_CPP_MIN_LOG_LEVEL: ${TF_CPP_MIN_LOG_LEVEL:-3}
    ports:
      - "8000:8000"
    restart: on-failure
