# the file contains a full setup for local QA run with NGINX
# profiles (scenarios):
#
# - qa: full run imitating prod setup (pulled prod images, no hot reload, nginx)
#
# run with: docker compose -f compose.base.yaml -f compose.qa.yaml --profile [[profile]] up


services:

  # include nginx
  nginx:
    profiles:
      - qa

  # include db
  db:
    profiles:
      - qa


  # backend overrides for qa
  backend:
    volumes:
      - staticfiles:/app/staticfiles    # static volume for shared access with nginx
      - media:/app/media                # ^ same for media
      - django_logs:/tmp/django         # persistent logs for debug
    environment:
      SHALLWE_BACKEND_DB_HOST: db       # override to talk to db container
    profiles:
      - qa


  # run a preserved frontend build
  frontend:
    command: node server.js
    depends_on:
      - backend
    profiles:
      - qa
