import React from "react";
import { InitMSW } from '@/lib/InitMSW';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const useMocks = process.env.NEXT_PUBLIC_SHALLWE_MOCK_API === 'true';

  return (
    <html lang="en">
      <body>
        {useMocks ? <InitMSW>{children}</InitMSW> : children}
      </body>
    </html>
  );
}
