# Generated by Django 5.0.1 on 2024-02-24 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shallwe_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilerentpreferences',
            name='max_budget',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='userprofilerentpreferences',
            name='min_budget',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
