# Generated by Django 5.0.1 on 2024-02-03 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shallwe_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(check=models.Q(('name__regex', '^[а-яА-ЯёЁіІїЇєЄґҐ`]{2,16}$')), name='user_profile_name_constraints', violation_error_message='Name should be: Cyrillic characters only, no spaces, 2-16 characters'),
        ),
    ]
