# Generated by Django 5.0.1 on 2024-02-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shallwe_locations', '0003_alter_location_city'),
        ('shallwe_profile', '0002_alter_userprofilerentpreferences_max_budget_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userprofilerentpreferences',
            constraint=models.CheckConstraint(check=models.Q(('max_rent_duration_level__gte', models.F('min_rent_duration_level'))), name='rent-prefs-max_rent_duration-gte-min_rent_duration', violation_error_message='max_rent_duration_level should be greater than or equal to min_rent_duration_level.'),
        ),
    ]
