# Generated by Django 5.0.1 on 2024-02-05 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shallwe_locations', '0003_alter_location_city'),
        ('shallwe_profile', '0002_userprofile_user_profile_name_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(),
        ),
        migrations.CreateModel(
            name='UserProfilePreferredLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shallwe_locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileRentPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_budget', models.PositiveSmallIntegerField()),
                ('max_budget', models.PositiveSmallIntegerField()),
                ('min_rent_duration_level', models.PositiveSmallIntegerField(choices=[(1, '<3m'), (2, '3m'), (3, '6m'), (4, 'y'), (5, '>y')], default=1)),
                ('max_rent_duration_level', models.PositiveSmallIntegerField(choices=[(1, '<3m'), (2, '3m'), (3, '6m'), (4, 'y'), (5, '>y')], default=5)),
                ('room_sharing_level', models.PositiveSmallIntegerField(choices=[(1, 'no'), (2, 'yes'), (3, 'only')], default=2)),
                ('locations', models.ManyToManyField(related_name='preferences', through='shallwe_profile.UserProfilePreferredLocations', to='shallwe_locations.location')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent_preferences', to='shallwe_profile.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofilepreferredlocations',
            name='related_preferences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shallwe_profile.userprofilerentpreferences'),
        ),
        migrations.AddConstraint(
            model_name='userprofilerentpreferences',
            constraint=models.CheckConstraint(check=models.Q(('min_budget__lte', models.F('max_budget'))), name='rent-prefs-profile-min-budget-lte-max-budget', violation_error_message='min_budget should be less than or equal to max_budget.'),
        ),
        migrations.AddConstraint(
            model_name='userprofilerentpreferences',
            constraint=models.CheckConstraint(check=models.Q(('min_budget__gte', 0), ('min_budget__lte', 99999)), name='rent-prefs-min-budget-range', violation_error_message='min_budget should be within the range [0, 99999].'),
        ),
        migrations.AddConstraint(
            model_name='userprofilerentpreferences',
            constraint=models.CheckConstraint(check=models.Q(('max_budget__gte', 0), ('max_budget__lte', 99999)), name='rent-prefs-max-budget-range', violation_error_message='max_budget should be within the range [0, 99999].'),
        ),
        migrations.AlterUniqueTogether(
            name='userprofilepreferredlocations',
            unique_together={('related_preferences', 'location')},
        ),
    ]
