# Generated by Django 5.0.1 on 2024-03-08 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shallwe_profile', '0004_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='interesttag',
            name='profile-about-interest-tag-name-constraint',
        ),
        migrations.RemoveConstraint(
            model_name='otheranimaltag',
            name='profile-about-other-animal-tag-name-constraint',
        ),
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='user-profile-name-constraints',
        ),
        migrations.AddConstraint(
            model_name='interesttag',
            constraint=models.CheckConstraint(check=models.Q(('name__regex', "^[а-яА-ЯёЁіІїЇєЄґҐ`\\'\\-\\s]{2,32}$")), name='profile-about-interest-tag-name-constraint', violation_error_message='Interest tag name must be only Cyrillic chars, hyphens and spaces, 2-32 chars'),
        ),
        migrations.AddConstraint(
            model_name='otheranimaltag',
            constraint=models.CheckConstraint(check=models.Q(('name__regex', "^[а-яА-ЯёЁіІїЇєЄґҐ`\\'\\-]{2,32}$")), name='profile-about-other-animal-tag-name-constraint', violation_error_message='Other animal tag name must be only Cyrillic chars and hyphens, 2-32 chars'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(check=models.Q(('name__regex', "^[а-яА-ЯёЁіІїЇєЄґҐ`\\']{2,16}$")), name='user-profile-name-constraints', violation_error_message='Name should be: Cyrillic characters only, no spaces, 2-16 characters'),
        ),
    ]
