name: 'CI/CD: Build, Test & Push Backend QA Docker Image'
# Builds the image with a version tag, tests inside the container, pushes if tests pass

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+a[0-9]*'
    paths:
      - 'shallwe_core/**'   # Only trigger if backend files changed
  workflow_dispatch:  # Allow manual trigger for testing the workflow


jobs:

  build-test-push:

    runs-on: ubuntu-latest
    env:
      # --- image info ---
      BACKEND_IMAGE_FULL: ${{ vars.IMAGE_REGISTRY_URL }}/${{ vars.IMAGE_REGISTRY_NAMESPACE }}/backend:${{ github.ref_name }}
      # --- backend globals ---
      SHALLWE_GLOBAL_SITE_URL_EXTERNAL: http://localhost:8000
      SHALLWE_GLOBAL_SITE_URL_INTERNAL: http://localhost:8000
      SHALLWE_GLOBAL_OAUTH_CLIENT_ID: 255892543568-1o2fma0nns066agr5a2m9uipfnmeneai.apps.googleusercontent.com
      SHALLWE_GLOBAL_OAUTH_CLIENT_SECRET: ${{ secrets.SHALLWE_GLOBAL_OAUTH_CLIENT_SECRET }}
      SHALLWE_GLOBAL_OAUTH_REDIRECT_URI: http://localhost:8000
      SHALLWE_GLOBAL_ENV_MODE: QA
      # --- django core ---
      SHALLWE_BACKEND_SECRET_KEY: citestkey123
      SHALLWE_BACKEND_DEBUG_ON: False
      SHALLWE_BACKEND_REST_BROWSABLE: False
      # --- entrypoint ---
      SHALLWE_BACKEND_ENTRYPOINT_AUTORUN: false
      SHALLWE_BACKEND_ENTRYPOINT_AUTOTEST: false
      # --- admin ---
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: admin123
      # --- database ---
      SHALLWE_BACKEND_DB_HOST: 172.17.0.1
      SHALLWE_BACKEND_DB_PORT: 5432
      SHALLWE_BACKEND_DB_NAME: cidb
      SHALLWE_BACKEND_TEST_DB_NAME: test_cidb
      SHALLWE_BACKEND_DB_USER: testuser
      SHALLWE_BACKEND_DB_PASS: testpass
      # --- network ---
      SHALLWE_BACKEND_ALLOWED_HOSTS: 127.0.0.1,localhost
      SHALLWE_BACKEND_ALLOWED_CIDR_NETS: 127.0.0.0/8,192.168.0.0/16
      SHALLWE_BACKEND_CSRF_TRUSTED_ORIGINS: http://localhost:8000
      SHALLWE_BACKEND_CORS_ALLOWED_ORIGINS: http://localhost:8000
      SHALLWE_BACKEND_CREDENTIALS_COOKIE_DOMAIN: localhost
      # --- deepface ---
      SHALLWE_BACKEND_DEEPFACE_MODELS: ssd, mtcnn, retinaface
      # --- logs ---
      TF_CPP_MIN_LOG_LEVEL: 3


    services:

      postgres:
        image: postgres:16.9-alpine
        env:
          POSTGRES_USER: ${{ env.SHALLWE_BACKEND_DB_USER }}
          POSTGRES_PASSWORD: ${{ env.SHALLWE_BACKEND_DB_PASS }}
          POSTGRES_DB: ${{ env.SHALLWE_BACKEND_DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5


    steps:

      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.IMAGE_REGISTRY_URL }}
          username: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.IMAGE_REGISTRY_TOKEN }}


      - name: Build Docker image
        run: |
          docker build \
            --build-arg SHALLWE_BACKEND_DEEPFACE_MODELS \
            -t $BACKEND_IMAGE_FULL ./shallwe_core


      - name: Run tests on Docker image
        run: |
          docker run --rm \
            --entrypoint "" \
            -e SHALLWE_GLOBAL_SITE_URL_EXTERNAL \
            -e SHALLWE_GLOBAL_SITE_URL_INTERNAL \
            -e SHALLWE_GLOBAL_OAUTH_CLIENT_ID \
            -e SHALLWE_GLOBAL_OAUTH_CLIENT_SECRET \
            -e SHALLWE_GLOBAL_OAUTH_REDIRECT_URI \
            -e SHALLWE_GLOBAL_ENV_MODE \
            -e SHALLWE_BACKEND_SECRET_KEY \
            -e SHALLWE_BACKEND_DEBUG_ON \
            -e SHALLWE_BACKEND_REST_BROWSABLE \
            -e SHALLWE_BACKEND_ENTRYPOINT_AUTORUN \
            -e SHALLWE_BACKEND_ENTRYPOINT_AUTOTEST \
            -e DJANGO_SUPERUSER_USERNAME \
            -e DJANGO_SUPERUSER_EMAIL \
            -e DJANGO_SUPERUSER_PASSWORD \
            -e SHALLWE_BACKEND_DB_HOST \
            -e SHALLWE_BACKEND_DB_PORT \
            -e SHALLWE_BACKEND_DB_NAME \
            -e SHALLWE_BACKEND_TEST_DB_NAME \
            -e SHALLWE_BACKEND_DB_USER \
            -e SHALLWE_BACKEND_DB_PASS \
            -e SHALLWE_BACKEND_ALLOWED_HOSTS \
            -e SHALLWE_BACKEND_ALLOWED_CIDR_NETS \
            -e SHALLWE_BACKEND_CSRF_TRUSTED_ORIGINS \
            -e SHALLWE_BACKEND_CORS_ALLOWED_ORIGINS \
            -e SHALLWE_BACKEND_CREDENTIALS_COOKIE_DOMAIN \
            -e SHALLWE_BACKEND_DEEPFACE_MODELS \
            -e TF_CPP_MIN_LOG_LEVEL \
            $BACKEND_IMAGE_FULL \
            sh -c "python3 ./shallwe_core/envconfig/parse_to_constants.py && python3 manage.py test --noinput -v 2"


      - name: Push Docker image if tests pass
        if: success()
        run: docker push $BACKEND_IMAGE_FULL
