# Generated by Django 4.2.7 on 2024-01-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('autocode', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('hierarchy', models.CharField(max_length=14, unique=True)),
                ('category', models.CharField(choices=[('a', 'Whole country'), ('r', 'Region'), ('c', 'City'), ('p', 'Other PPL'), ('d', 'City district')], max_length=1)),
                ('region_name', models.CharField(max_length=32, null=True)),
                ('subregion_name', models.CharField(max_length=32, null=True)),
                ('ppl_name', models.CharField(max_length=32, null=True)),
                ('district_name', models.CharField(max_length=32, null=True)),
                ('search_name', models.CharField(max_length=32)),
                ('city', models.ForeignKey(db_column='city_autocode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shallwe_locations.location')),
            ],
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('category', 'd'), ('city_id__isnull', False), ('district_name__isnull', False), ('ppl_name__isnull', False), ('subregion_name__isnull', False), ('region_name__isnull', False)), models.Q(('category', 'd'), _negated=True), _connector='OR'), name='city_district_valid_fields'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('category', 'c'), ('category', 'p'), _connector='OR'), ('city_id__isnull', True), ('district_name__isnull', True), ('ppl_name__isnull', False), ('subregion_name__isnull', False), ('region_name__isnull', False)), models.Q(('category__in', ['c', 'p']), _negated=True), _connector='OR'), name='ppl_valid_fields'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('category', 'r'), ('city_id__isnull', True), ('district_name__isnull', True), ('ppl_name__isnull', True), ('subregion_name__isnull', True), ('region_name__isnull', False)), models.Q(('category', 'r'), _negated=True), _connector='OR'), name='region_valid_fields'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('category', 'a'), ('city_id__isnull', True), ('district_name__isnull', True), ('ppl_name__isnull', True), ('subregion_name__isnull', True), ('region_name__isnull', True)), models.Q(('category', 'a'), _negated=True), _connector='OR'), name='country_valid_fields'),
        ),
    ]
