# Generated by Django 5.0.1 on 2024-01-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shallwe_locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['hierarchy']},
        ),
    ]
