# Generated by Django 5.0.1 on 2024-01-22 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shallwe_locations', '0002_alter_location_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(db_column='city_autocode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='districts', to='shallwe_locations.location'),
        ),
    ]
